# User config
author: "pine_thank_you"
#tagline: ""
description: "ðŸ’œ Hi, I'm chasey"
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "dahewoo@daum.net"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/daheewoo"
blog : "https://w94dev.tistory.com/"

# Site config
# baseurl: "/daheewoo.github.io"
baseurl: "/"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
